### ISSUE TITLE
32-bit libraries

### ISSUE THREAD

**Issue by lnicola** [yurikoles-aur/android-studio-beta#7]
Hello!

Does Android Studio really need (or started to) `lib32-zlib`, `lib32-gcc-libs` and `lib32-bzip2`? I've used the previous versions and they seemed to work fine without the 32-bit libraries.

**Comment by fschuetz04** [comment]
Also, the standard AUR Android Studio version has different dependencies: https://github.com/kordianbruck/arch-aur-android-studio. Based on what are these dependencies set?

**Comment by yurikoles** [comment]
It's based on my research on [NixOS](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/android-studio/common.nix) and [Gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/android-studio/android-studio-4.1.3.0.201.7199119.ebuild) packages.
